### ISSUE TITLE
Did you ever use this in real world?

### ISSUE THREAD

**Issue by dyske** [warmfusion/Tilly-The-Printerbot#6]
Sorry, I couldn't find any other ways to contact you. I'm wondering if you ever found a real-world use case for this. I came across your printer because I'm looking for a way to print restaurant delivery orders received on a website. The restaurant industry (at least in the US) has chosen thermal printers as the universal protocol to send orders into kitchens. So, every order taking services like Seamless, Uber Eats, Caviar, has their own little thermal printer in restaurant kitchens. So, a typical restaurant in NYC would have at least two of them: one for their in-house POS and another for some sort of delivery service. But I don't see a good solution for sending orders from restaurants' own websites. Your Tilly could work for that. If your printer can print messages from Slack, I can then send a Webhook message to Slack from the web server, and your printer would print out the order. The kitchen staff would then cut it and stick it on their board to be processed.

**Comment by warmfusion** [comment]
To be honest, just bypass Slack entirely. The API was horrible to work with at the time (maybe still?)
The printer protocol is very simple, and using something like an ESP8266 you'd be able ot make a wifi enabled printer that can read data from anything you need.

I'd maybe suggest MQTT queue that gets populated from some central system. You probably want to handle 'errors' and 'reprints' (for instance when roll gets stuck/runs out etc) so thers more there than just printing a message from time to time.

Slack isn't the right choice for your centralised list. :-)

**Comment by dyske** [comment]
Thank you for your suggestions!
